Revert "chore(dispatcharr): migrate to modular deployment (#1138)"
This reverts commit 79916c0236df8a5cb27d7a14df634225782b7ad6.

Need to update to 0.22.0 prior to to migrating due to DB updates...

2026-04-01 14:30:19,000 DEBUG uwsgi.requests Worker ID: 2 GET 500 /api/channels/channels/?page=1&page_size=500 8ms
2026-04-01 14:30:19,368 ERROR django.request Internal Server Error: /proxy/ts/status
Traceback (most recent call last):
  File "/dispatcharrpy/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column accounts_user.stream_limit does not exist
LINE 1: ..."."custom_properties", "accounts_user"."api_key", "accounts_...
                                                             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/dispatcharrpy/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/dispatcharrpy/lib/python3.13/site-packages/django/core/handlers/base.py", line 198, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/dispatcharrpy/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/dispatcharrpy/lib/python3.13/site-packages/django/views/generic/base.py", line 106, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dispatcharrpy/lib/python3.13/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "/dispatcharrpy/lib/python3.13/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/dispatcharrpy/lib/python3.13/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/dispatcharrpy/lib/python3.13/site-packages/rest_framework/views.py", line 503, in dispatch
    self.initial(request, *args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dispatcharrpy/lib/python3.13/site-packages/rest_framework/views.py", line 420, in initial
    self.perform_authentication(request)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/dispatcharrpy/lib/python3.13/site-packages/rest_framework/views.py", line 330, in perform_authentication
    request.user
  File "/dispatcharrpy/lib/python3.13/site-packages/rest_framework/request.py", line 232, in user
    self._authenticate()
    ~~~~~~~~~~~~~~~~~~^^
  File "/dispatcharrpy/lib/python3.13/site-packages/rest_framework/request.py", line 385, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/dispatcharrpy/lib/python3.13/site-packages/rest_framework_simplejwt/authentication.py", line 51, in authenticate
    return self.get_user(validated_token), validated_token
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/dispatcharrpy/lib/python3.13/site-packages/rest_framework_simplejwt/authentication.py", line 132, in get_user
    user = self.user_model.objects.get(**{api_settings.USER_ID_FIELD: user_id})
  File "/dispatcharrpy/lib/python3.13/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/dispatcharrpy/lib/python3.13/site-packages/django/db/models/query.py", line 635, in get
    num = len(clone)
  File "/dispatcharrpy/lib/python3.13/site-packages/django/db/models/query.py", line 372, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/dispatcharrpy/lib/python3.13/site-packages/django/db/models/query.py", line 2000, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dispatcharrpy/lib/python3.13/site-packages/django/db/models/query.py", line 95, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/dispatcharrpy/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1624, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/dispatcharrpy/lib/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/dispatcharrpy/lib/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/dispatcharrpy/lib/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dispatcharrpy/lib/python3.13/site-packages/django/db/utils.py", line 94, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/dispatcharrpy/lib/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column accounts_user.stream_limit does not exist
LINE 1: ..."."custom_properties", "accounts_user"."api_key", "accounts_...