chore(streamflow): disable again due to root
supervisord is running as root

2025-12-14 14:28:51.484725000
For help, use /usr/bin/supervisord -h
2025-12-14 14:28:51.484675000
Error: Can't drop privilege as nonroot user